version: '3.8'
services:
  data-pasien-app:
    build: .                           
    # image: php:8.2-cli               
    container_name: data-pasien-service
    ports:
      - "8001:8000"
    # volumes:       
    #   - .:/app     
    working_dir: /app